name: AWS Python 3.7.1
on: [push]
jobs:
  buil:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7.1
      uses: actions/setup-python@v1
      with:
        python-version: 3.7.1
    
    - name: Install dependencies
      run: |
        make install-aws
