name: AWS Python 3.7.10
on: [push]
jobs:
  buil:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7.15
      uses: actions/setup-python@v1
      with:
        python-version: 3.7.15
    
    - name: Install dependencies
      run: |
        make install-aws
    - name: lint
      run: |
        make lint
    - name: test
      run: |
        make test
    - name: format
      run: |
        make format